// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import ClientSideLayout from "@/components/Layout/ClientSideLayout";
import { DarkModeProvider } from "@/contexts/DarkModeContext";
import Loading from "@/components/Loading";
import { Roboto } from "@next/font/google";

export const metadata: Metadata = {
  title: "Task Minder - Rifqi",
  description: "Generated by Rifqi Taufiqurrohman",
  icons: {
    icon: "/rifqi.jpg",
  },
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="antialiased">
        <DarkModeProvider>
          <Loading>
            <ClientSideLayout>{children}</ClientSideLayout>
          </Loading>
        </DarkModeProvider>
      </body>
    </html>
  );
}
